server:
  port: 8080

spring:
  application:
    name: email-processor-consumer

aws:
  region: ${AWS_DEFAULT_REGION:us-west-1}

sqs:
  queue-url: ${SQS_QUEUE_URL:}

s3:
  bucket-name: ${S3_BUCKET_NAME:}

logging:
  level:
    com.emailprocessor: DEBUG
    software.amazon.awssdk: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      service: microservice-2
    distribution:
      percentiles-histogram:
        http.server.requests: true
